languageCode = "en-us"
title = "FilePond Documentation"
baseURL = "https://pqina.nl/filepond/docs/"
canonifyURLs = true
theme = "cupper"
publishDir = "filepond/docs"

[params]
  description = "**FilePond** Documentation"
  codePenUser = "rikschennink"
  stylesheets = ["css/cupper-happy.css"]
